CREATE TABLE IF NOT EXISTS "FileWrite" (
	"id" INTEGER NOT NULL UNIQUE,
	"trace" INTEGER NOT NULL UNIQUE,
	"process" INTEGER NOT NULL,
	"file" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("trace") REFERENCES "ImmutableTrace"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "ImmutableTrace" (
	"id" INTEGER NOT NULL UNIQUE,
	"created" DATETIME NOT NULL,
	PRIMARY KEY("id")	
);

CREATE TABLE IF NOT EXISTS "Process" (
	"id" INTEGER NOT NULL UNIQUE,
	"trace" INTEGER NOT NULL,
	"origin" TEXT NOT NULL,
	"parent" INTEGER,
	"user" TEXT NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("trace") REFERENCES "ImmutableTrace"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "FileRead" (
	"id" INTEGER NOT NULL UNIQUE,
	"trace" INTEGER NOT NULL,
	"process" INTEGER NOT NULL,
	"file" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("trace") REFERENCES "ImmutableTrace"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "File" (
	"id" INTEGER NOT NULL UNIQUE,
	"trace" INTEGER NOT NULL,
	"path" TEXT NOT NULL,
	"hash" TEXT NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("trace") REFERENCES "ImmutableTrace"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
