[package]
name = "sdsnoop"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_bindgen = "0.9.0-alpha"
serde = { version = "1", features = ["derive"] }
linkme = "0.3"

[lib]
name = "sdsnoop"
crate-type = ["cdylib"]
